# Site settings
title: STUPS Landscape
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zalando-stups.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  zalando-stups
contacts:
  - name: "Tobias Sarnowski"
    email: tobias.sarnowski@zalando.de
  - name: "Henning Jacobs"
    email: henning.jacobs@zalando.de

sass:
  sass_dir: css

permalink: "/:title"

# Build settings
markdown: kramdown
